### ISSUE TITLE
Need help, can you explain?

### ISSUE THREAD

**Issue by bostjannagode** [stevstrong/Ethernet_STM32#1]
Dear, im using Stm32Duino cores and would like to try your Ethernet_STM32 library. I have simple sketch:

> #include <C:\Users\nbostjan\Documents\Arduino\hardware\Arduino_STM32-master\STM32F1\libraries\SPI\src\SPI.h>
> #include "C:\Users\nbostjan\Documents\Arduino\hardware\Arduino_STM32-master\STM32F1\libraries\Ethernet_STM32\src\Ethernet_STM32.h"
> const int chipSelect = PA4;   
> byte *id5 =  (byte *) (0x1FFFF7EC);
> byte *id4 =  (byte *) (0x1FFFF7EC+0x01);
> byte *id3 =  (byte *) (0x1FFFF7EC+0x02);
> byte *id2 =  (byte *) (0x1FFFF7EC+0x03);
> byte *id1 =  (byte *) (0x1FFFF7EC+0x04);
> byte mac[] = { 0xEA, *id1, *id2, *id3, *id4, *id5 };
> unsigned int localPort = 8000;
> EthernetServer server(localPort);
> SPIClass mSpi(1); //USING SPI2 PB12-PB15
> void setup()
> {
>   delay(3000);
>   Ethernet.init(mSpi, PB12);
>   Ethernet.begin(mac);
>   server.begin();
> }

But it gives me a bunch of errors:
Compiling 'ethernet' for 'Generic STM32F103C series'
 
ethernet.cpp.o*: In function _GLOBAL__sub_I_id5
ethernet.ino: 21: warning: undefined reference to `EthernetServer::EthernetServer(unsigned short)
 
ethernet.cpp.o*: In function SOCKETClass::init(SPIClass&, unsigned char)
socket.h: 18: warning: undefined reference to `W5500Class::init(SPIClass&, unsigned char)
 
ethernet.cpp.o*: In function setup()
ethernet.ino: 29: warning: undefined reference to `EthernetClass::begin(unsigned char*, unsigned long, unsigned long)
ethernet.ino: 31: warning: undefined reference to `SOCKETClass::w5500
ethernet.ino: 31: warning: undefined reference to `Ethernet
ethernet.ino: 31: warning: undefined reference to `EthernetServer::begin()

**Comment by stevstrong** [comment]
This library officially supports only Arduino IDE in combination with this core: 
https://github.com/rogerclarkmelbourne/Arduino_STM32
or:
https://github.com/stevstrong/Arduino_STM32

It looks like you are not using Arduino IDE, and/or you did not install correctly one of the mentioned cores.
Please visit this site for the installation procedure: http://wiki.stm32duino.com/index.php?title=Installation

Should you have any further question, please post here: www.stm32duino.com
